language: node_js

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

sudo: false

node_js:
  - '6'

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g yarn

before_script:
  - npm prune

install:
  - yarn

script:
  - npm run lint
  - npm run test